### PR TITLE
Experimental features to Dev for more testing

### PR DESCRIPTION
**Pull request by vinceeleazar**

### CODE REVIEW

**Review by vinceeleazar — COMMENTED** [review]
can be considered stale if the changes are not enough for testing yet.

**Review by Aroueterra — DISMISSED** [review]
Mostly good improvements.

**Review by Aroueterra — DISMISSED** [review]

**Review by vinceeleazar — COMMENTED** [review]
Almost there bois just need to implement the server and client interaction,

**Review by Aroueterra — DISMISSED** [review]
Nothing essential is lost via merge.

**Review by Aroueterra — APPROVED** [review]

**Pull request merged**
